services: 
    rust-web:
        build: .
        volumes:
            - ./app:/usr/src/app
            - cargo-cache:/usr/local/cargo/registry
        working_dir: /usr/src/app
        tty: true
        stdin_open: true
        ports:
            - "3000:3000"

volumes:
    cargo-cache: